/* Auto-generated by genmsg_cpp for file /home/alessio/RosWorkspace/sandbox/action_controller/msg/MultiDofFollowJointTrajectoryGoal.msg */
#ifndef ACTION_CONTROLLER_MESSAGE_MULTIDOFFOLLOWJOINTTRAJECTORYGOAL_H
#define ACTION_CONTROLLER_MESSAGE_MULTIDOFFOLLOWJOINTTRAJECTORYGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "trajectory_msgs/MultiDOFJointTrajectory.h"

namespace action_controller
{
template <class ContainerAllocator>
struct MultiDofFollowJointTrajectoryGoal_ {
  typedef MultiDofFollowJointTrajectoryGoal_<ContainerAllocator> Type;

  MultiDofFollowJointTrajectoryGoal_()
  : trajectory()
  {
  }

  MultiDofFollowJointTrajectoryGoal_(const ContainerAllocator& _alloc)
  : trajectory(_alloc)
  {
  }

  typedef  ::trajectory_msgs::MultiDOFJointTrajectory_<ContainerAllocator>  _trajectory_type;
   ::trajectory_msgs::MultiDOFJointTrajectory_<ContainerAllocator>  trajectory;


  typedef boost::shared_ptr< ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MultiDofFollowJointTrajectoryGoal
typedef  ::action_controller::MultiDofFollowJointTrajectoryGoal_<std::allocator<void> > MultiDofFollowJointTrajectoryGoal;

typedef boost::shared_ptr< ::action_controller::MultiDofFollowJointTrajectoryGoal> MultiDofFollowJointTrajectoryGoalPtr;
typedef boost::shared_ptr< ::action_controller::MultiDofFollowJointTrajectoryGoal const> MultiDofFollowJointTrajectoryGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace action_controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "70ac13f44ce8dd6df296056f97e1a1fa";
  }

  static const char* value(const  ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x70ac13f44ce8dd6dULL;
  static const uint64_t static_value2 = 0xf296056f97e1a1faULL;
};

template<class ContainerAllocator>
struct DataType< ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "action_controller/MultiDofFollowJointTrajectoryGoal";
  }

  static const char* value(const  ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# The joint trajectory to follow\n\
trajectory_msgs/MultiDOFJointTrajectory trajectory\n\
\n\
================================================================================\n\
MSG: trajectory_msgs/MultiDOFJointTrajectory\n\
# The header is used to specify the reference time for the trajectory durations\n\
Header header\n\
\n\
#A representation of a multi-dof joint trajectory\n\
string[] joint_names\n\
MultiDOFJointTrajectoryPoint[] points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: trajectory_msgs/MultiDOFJointTrajectoryPoint\n\
geometry_msgs/Transform[] transforms\n\
duration time_from_start\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Transform\n\
# This represents the transform between two coordinate frames in free space.\n\
\n\
Vector3 translation\n\
Quaternion rotation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.trajectory);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MultiDofFollowJointTrajectoryGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::action_controller::MultiDofFollowJointTrajectoryGoal_<ContainerAllocator> & v) 
  {
    s << indent << "trajectory: ";
s << std::endl;
    Printer< ::trajectory_msgs::MultiDOFJointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.trajectory);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ACTION_CONTROLLER_MESSAGE_MULTIDOFFOLLOWJOINTTRAJECTORYGOAL_H

