/* Auto-generated by genmsg_cpp for file /home/alessio/RosWorkspace/sandbox/action_controller/msg/MultiDofFollowJointTrajectoryActionFeedback.msg */
#ifndef ACTION_CONTROLLER_MESSAGE_MULTIDOFFOLLOWJOINTTRAJECTORYACTIONFEEDBACK_H
#define ACTION_CONTROLLER_MESSAGE_MULTIDOFFOLLOWJOINTTRAJECTORYACTIONFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "actionlib_msgs/GoalStatus.h"
#include "action_controller/MultiDofFollowJointTrajectoryFeedback.h"

namespace action_controller
{
template <class ContainerAllocator>
struct MultiDofFollowJointTrajectoryActionFeedback_ {
  typedef MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> Type;

  MultiDofFollowJointTrajectoryActionFeedback_()
  : header()
  , status()
  , feedback()
  {
  }

  MultiDofFollowJointTrajectoryActionFeedback_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , status(_alloc)
  , feedback(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::actionlib_msgs::GoalStatus_<ContainerAllocator>  _status_type;
   ::actionlib_msgs::GoalStatus_<ContainerAllocator>  status;

  typedef  ::action_controller::MultiDofFollowJointTrajectoryFeedback_<ContainerAllocator>  _feedback_type;
   ::action_controller::MultiDofFollowJointTrajectoryFeedback_<ContainerAllocator>  feedback;


  typedef boost::shared_ptr< ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MultiDofFollowJointTrajectoryActionFeedback
typedef  ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<std::allocator<void> > MultiDofFollowJointTrajectoryActionFeedback;

typedef boost::shared_ptr< ::action_controller::MultiDofFollowJointTrajectoryActionFeedback> MultiDofFollowJointTrajectoryActionFeedbackPtr;
typedef boost::shared_ptr< ::action_controller::MultiDofFollowJointTrajectoryActionFeedback const> MultiDofFollowJointTrajectoryActionFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace action_controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bb90301ebf9ac17d9c3bcafa7a141cba";
  }

  static const char* value(const  ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbb90301ebf9ac17dULL;
  static const uint64_t static_value2 = 0x9c3bcafa7a141cbaULL;
};

template<class ContainerAllocator>
struct DataType< ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "action_controller/MultiDofFollowJointTrajectoryActionFeedback";
  }

  static const char* value(const  ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
MultiDofFollowJointTrajectoryFeedback feedback\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: action_controller/MultiDofFollowJointTrajectoryFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
Header header\n\
string[] joint_names\n\
moveit_msgs/MultiDOFJointTrajectoryPoint desired\n\
moveit_msgs/MultiDOFJointTrajectoryPoint actual\n\
moveit_msgs/MultiDOFJointTrajectoryPoint error\n\
\n\
\n\
================================================================================\n\
MSG: moveit_msgs/MultiDOFJointTrajectoryPoint\n\
geometry_msgs/Transform[] transforms\n\
duration time_from_start\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Transform\n\
# This represents the transform between two coordinate frames in free space.\n\
\n\
Vector3 translation\n\
Quaternion rotation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.status);
    stream.next(m.feedback);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MultiDofFollowJointTrajectoryActionFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::action_controller::MultiDofFollowJointTrajectoryActionFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
s << std::endl;
    Printer< ::actionlib_msgs::GoalStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
    s << indent << "feedback: ";
s << std::endl;
    Printer< ::action_controller::MultiDofFollowJointTrajectoryFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.feedback);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ACTION_CONTROLLER_MESSAGE_MULTIDOFFOLLOWJOINTTRAJECTORYACTIONFEEDBACK_H

